### PR TITLE
Relicense mod under GPL3

### LINKED ISSUE #79: Relicense/license
Currently all rights reserved. Might license to LGPL, been interested in these copyleft licenses. There are some complaints about compatibility with the GPL series of licenses but I think that's not an issue with LGPL. Not like any Minecraft mods have had their day in court anyway.

### PR DESCRIPTION
**Pull request by xbony2**
With the consent of all contributor, I would like to ask each of you for your permission to license this mod under GPL3.

* [x] @xbony2 : I consent to this change
* [x] @Hubry 
* [x] @elifoster 
* [x] @Vexatos 

(This would close #79)

### CODE REVIEW

**Comment by Hubry** [comment]
I consent to the relicense.

**Comment by Vexatos** [comment]
I consent.

**Comment by elifoster** [comment]
I consent

**Comment by xbony2** [comment]
Yeet

**Pull request merged**
